# Generated by Django 5.2.7 on 2025-10-05 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='jd_files/')),
                ('primary_skills', models.TextField(blank=True)),
                ('secondary_skills', models.TextField(blank=True)),
                ('soft_skills', models.TextField(blank=True)),
                ('role_category', models.CharField(blank=True, max_length=255, null=True)),
                ('experience_level', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
