# Generated by Django 5.2.7 on 2025-10-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdescription',
            old_name='primary_skills',
            new_name='all_skills',
        ),
        migrations.RenameField(
            model_name='jobdescription',
            old_name='secondary_skills',
            new_name='key_responsibilities',
        ),
        migrations.RenameField(
            model_name='jobdescription',
            old_name='soft_skills',
            new_name='qualifications',
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='skill_categories',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
