# Generated by Django 5.0.7 on 2025-10-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_primary_skills_jobdescription_all_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='linkedin_search_string',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='linkedin_skills_string',
            field=models.TextField(blank=True),
        ),
    ]
