# Generated by Django 5.0.7 on 2025-10-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_jobdescription_linkedin_search_string_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='candidate_databases/')),
                ('total_candidates', models.IntegerField(default=0)),
                ('file_name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
