# Generated by Django 5.2.7 on 2025-11-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_googlesheetdatabase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CandidateDatabase',
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='jd_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='jd_files/'),
        ),
    ]
