# Generated by Django 5.0.7 on 2025-11-10 09:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_delete_candidatedatabase_jobdescription_jd_text_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('JD_UPLOAD', 'Job Description Upload'), ('JD_VIEW', 'Job Description View'), ('JD_DELETE', 'Job Description Delete'), ('SHEET_ADD', 'Google Sheet Add'), ('SHEET_SYNC', 'Google Sheet Sync'), ('SHEET_DELETE', 'Google Sheet Delete'), ('MATCH_RUN', 'Candidate Match Run'), ('FILE_DOWNLOAD', 'File Download'), ('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('PERMISSION_DENIED', 'Permission Denied')], max_length=50)),
                ('target_model', models.CharField(blank=True, max_length=100)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='googlesheetdatabase',
            options={'ordering': ['-created_at'], 'permissions': [('can_view_all_sheets', 'Can view all Google Sheets'), ('can_share_sheets', 'Can share sheets with other users')]},
        ),
        migrations.AlterModelOptions(
            name='jobdescription',
            options={'ordering': ['-created_at'], 'permissions': [('can_view_all_jds', 'Can view all job descriptions'), ('can_delete_any_jd', 'Can delete any job description')]},
        ),
        migrations.RenameField(
            model_name='googlesheetdatabase',
            old_name='added_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='jobdescription',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='googlesheetdatabase',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='google_sheets', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='googlesheetdatabase',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of this database'),
        ),
        migrations.AddField(
            model_name='googlesheetdatabase',
            name='is_shared',
            field=models.BooleanField(default=False, help_text='Allow other users to use this sheet for matching'),
        ),
        migrations.AddField(
            model_name='googlesheetdatabase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='job_descriptions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='googlesheetdatabase',
            name='name',
            field=models.CharField(help_text='Name for this candidate database', max_length=200),
        ),
        migrations.AlterField(
            model_name='googlesheetdatabase',
            name='sheet_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='googlesheetdatabase',
            name='sheet_url',
            field=models.URLField(help_text='Full Google Sheets URL', max_length=500, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='experience_level',
            field=models.CharField(blank=True, default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='jds/'),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='role_category',
            field=models.CharField(blank=True, default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AddIndex(
            model_name='googlesheetdatabase',
            index=models.Index(fields=['created_by', '-created_at'], name='base_google_created_216270_idx'),
        ),
        migrations.AddIndex(
            model_name='googlesheetdatabase',
            index=models.Index(fields=['is_active', 'is_shared'], name='base_google_is_acti_85ba8e_idx'),
        ),
        migrations.AddIndex(
            model_name='jobdescription',
            index=models.Index(fields=['created_by', '-created_at'], name='base_jobdes_created_fb4ec8_idx'),
        ),
        migrations.AddIndex(
            model_name='jobdescription',
            index=models.Index(fields=['is_active'], name='base_jobdes_is_acti_4173b6_idx'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-timestamp'], name='base_auditl_user_id_e09b14_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', '-timestamp'], name='base_auditl_action_7a99d6_idx'),
        ),
    ]
